"""Menu-based structure-invention data (U5).

Scope ladder (TECHNICAL_GUIDE §14 — "simplest thing that exhibits the phenomenon";
§10 defines invention as an ABSENT slot going concrete during denoising):

  1. THIS MODULE: menu-based activation. Given an unsolvable fixed graph and a
     procedurally generated menu of K candidate augmentations (aux variable ``u``
     with a defining factor + insertion coefficients), exactly one of which makes
     the graph solvable, the policy must pick the right invention.
  2. OUT OF SCOPE: free-form expression invention (emitting an arbitrary defining
     expression). The menu formulation is the honest preliminary rung.

Each :class:`Candidate` is a complete augmentation recipe; :func:`build_menu`
certifies every distractor unsolvable before it enters the menu. HOW it certifies
depends on the graph, and the certificate is recorded per instance:

* Linear graphs (sources ``"toys"``/``"aux_required"``): an exact symbolic rank
  check — ``certificate="exact"``; "exactly one solvable option" is a theorem
  about the data.
* Nonlinear graphs (source ``"nonlinear"``): the rank check does not apply, so
  "unsolvable" means "not solved by the reference-family solver
  (:class:`~marc.eval.solver.GradientRefinementSolver` + :class:`~marc.cas.checker.Checker`)
  at the probe budget" (``DEFAULT_PROBE``: ``n_seeds * k_refine`` random
  restarts). Real roots may still exist outside the probe's reach — that is why
  these instances carry ``certificate="empirical"`` with the probe config
  attached, an empirical claim at a stated budget, not a theorem.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from types import SimpleNamespace
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import sympy as sp
import torch

from marc.cas.checker import Checker
from marc.eval.solver import GradientRefinementSolver
from marc.graph.graph import FactorGraph
from marc.graph.schema import Edge, FactorNode, VariableNode

from .schema import ABSENT, PaddedGraph, SlotType

#: bump when generated bytes change for identical seeds. 2: gold insert-coefficient
#: support is randomized per instance (kills the support-matching shortcut) and the
#: "nonlinear" source exists.
DATA_VERSION: int = 2

SOURCES: Tuple[str, ...] = ("toys", "aux_required", "nonlinear")

# reference solver — must match run_invention_eval.py and train_structure_policy.py
REFERENCE_SOLVER = {"name": "refine", "k_refine": 4, "polish_steps": 4000}

#: budget for the empirical unsolvability probe: n_seeds solvers x k_refine
#: restarts each. Cheaper than REFERENCE_SOLVER on purpose (asymmetric budgets:
#: gold solvability is verified at eval grade, distractor unsolvability at probe
#: grade — a false "solvable" distractor is worse than a slow probe).
DEFAULT_PROBE = {"n_seeds": 3, "k_refine": 4, "steps": 300, "polish_steps": 400}


@dataclass(frozen=True)
class Candidate:
    """One augmentation recipe: add latent ``aux_var`` with a defining factor and
    insert it (with the given coefficients) into a subset of fixed-graph factors.

    The defining factor is the scalar pin ``"u - (pin_value)"`` unless
    ``defining_expression`` is set, in which case that expression (which must
    mention ``aux_var``) is the defining factor — e.g. ``"u - (x - y)"`` couples
    the aux to the fixed variables instead of pinning it to a constant.
    ``pin_value`` is retained either way (= the aux value at the gold solution
    for gold candidates) so downstream features stay well-defined.
    """

    aux_var: str                      # always "u"
    pin_value: float                  # v in the defining factor "u - (v)"
    insert_coeffs: Dict[str, float]   # fixed-graph factor_id -> coefficient of u
    defining_expression: Optional[str] = None  # appended LAST: positional back-compat

    def __post_init__(self) -> None:
        if self.defining_expression is not None:
            names = {s.name for s in sp.sympify(self.defining_expression).free_symbols}
            if self.aux_var not in names:
                raise ValueError(
                    f"defining_expression {self.defining_expression!r} does not "
                    f"mention aux_var {self.aux_var!r}"
                )

    def apply(self, fixed: FactorGraph) -> FactorGraph:
        """Build the augmented graph. Pure — ``fixed`` is not mutated."""
        variables = [VariableNode(v.id, v.value) for v in fixed.variables]
        factors: List[FactorNode] = []
        edges = [Edge(e.variable_id, e.factor_id, e.coefficient) for e in fixed.edges]
        known = {f.id for f in fixed.factors}
        unknown = set(self.insert_coeffs) - known
        if unknown:
            raise ValueError(f"insert_coeffs reference unknown factors: {sorted(unknown)}")
        if "aux" in known or any(v.id == self.aux_var for v in fixed.variables):
            raise ValueError("fixed graph already contains an 'aux' factor or the aux variable")
        for f in fixed.factors:
            c = self.insert_coeffs.get(f.id)
            if c is None:
                factors.append(FactorNode(f.id, f.expression))
            else:
                factors.append(FactorNode(f.id, f"({f.expression}) + ({c})*{self.aux_var}"))
                edges.append(Edge(self.aux_var, f.id, float(c)))
        variables.append(VariableNode(self.aux_var))
        if self.defining_expression is None:
            factors.append(FactorNode("aux", f"{self.aux_var} - ({self.pin_value})"))
            edges.append(Edge(self.aux_var, "aux", 1.0))
        else:
            expr = sp.sympify(self.defining_expression)
            factors.append(FactorNode("aux", self.defining_expression))
            fixed_ids = {v.id for v in fixed.variables}
            for s in sorted(expr.free_symbols, key=lambda s: s.name):
                if s.name != self.aux_var and s.name not in fixed_ids:
                    continue
                d = sp.diff(expr, s)
                edges.append(Edge(s.name, "aux", float(d) if d.is_number else 1.0))
        return FactorGraph(variables=variables, factors=factors, edges=edges)


@dataclass
class InventionInstance:
    """A fixed (inconsistent) graph plus a K-candidate menu with one gold fix."""

    id: str
    family: str
    seed: int
    fixed_graph: FactorGraph
    candidates: List[Candidate]        # length K, gold at gold_idx (shuffled per seed)
    gold_idx: int
    aux_value: float                   # value of u in the augmented gold solution
    solution: Dict[str, float] = field(default_factory=dict)  # augmented gold incl. u
    certificate: str = "exact"         # "exact" (rank theorem) | "empirical" (probe)
    certificate_config: Optional[dict] = None  # probe budget + honest claim wording


def _is_inconsistent(graph: FactorGraph) -> bool:
    """Exact certificate that a *linear* factor graph has no solution.

    rank(A) < rank([A|b]) for the system A x = b read off the factor expressions.
    Raises (sympy NonlinearError, a ValueError) on nonlinear factors — callers that
    may see nonlinear graphs go through :func:`certify_unsolvable` instead.
    """
    # ponytail: self-contained ~10-line certificate; deliberately NOT imported from
    # marc/data/aux_required.py so this module works on main today.
    syms = [sp.Symbol(v.id) for v in graph.variables]
    exprs = [sp.sympify(f.expression) for f in graph.factors]
    A, b = sp.linear_eq_to_matrix(exprs, syms)
    return A.rank() < A.row_join(b).rank()


def _solvable_at_eval_grade(graph: FactorGraph, *, rng_seed: int) -> bool:
    """Best-of-k solve at the REFERENCE_SOLVER budget + Checker gate — the same
    grade run_invention_eval.py holds every arm to. Used for GOLD solvability."""
    solver = GradientRefinementSolver(
        seed=rng_seed, polish_steps=REFERENCE_SOLVER["polish_steps"]
    )
    prob = SimpleNamespace(graph=graph, metadata={})
    cands = solver.sample(prob, REFERENCE_SOLVER["k_refine"])
    return Checker().first_accepted(graph, cands) is not None


def certify_unsolvable(
    graph: FactorGraph, *, rng_seed: int, probe: dict = DEFAULT_PROBE
) -> dict:
    """Certify a graph unsolvable; returns ``{"unsolvable": bool, "method": str}``.

    Linear graphs get the exact rank certificate (``method="linear_rank"`` — a
    theorem). When sympy rejects the graph as nonlinear, fall back to an
    empirical probe (``method="empirical_probe"``): ``n_seeds * k_refine``
    refine restarts, any Checker-accepted candidate means solvable. An
    "unsolvable" probe verdict only means the reference-family solver failed at
    this budget — real roots may exist. Callers must surface that honestly
    (see ``InventionInstance.certificate``).
    """
    try:
        return {"unsolvable": _is_inconsistent(graph), "method": "linear_rank"}
    except (ValueError, sp.PolynomialError):
        pass  # nonlinear graph (sympy NonlinearError <= ValueError) -> probe
    prob = SimpleNamespace(graph=graph, metadata={})
    checker = Checker()
    for s in range(probe["n_seeds"]):
        solver = GradientRefinementSolver(
            steps=probe["steps"], polish_steps=probe["polish_steps"], seed=rng_seed + s
        )
        cands = solver.sample(prob, probe["k_refine"])
        if checker.first_accepted(graph, cands) is not None:
            return {"unsolvable": False, "method": "empirical_probe"}
    return {"unsolvable": True, "method": "empirical_probe"}


def _candidate_key(c: Candidate) -> Tuple:
    return (
        float(c.pin_value),
        tuple(sorted(c.insert_coeffs.items())),
        c.defining_expression,
    )


def build_menu(
    fixed: FactorGraph,
    gold_candidate: Candidate,
    K: int,
    rng: random.Random,
    hard_negatives: bool = True,
) -> Tuple[List[Candidate], int]:
    """Assemble a K-candidate menu around the gold fix; returns (menu, gold_idx).

    Distractors: random nonempty factor subsets + coefficients from {-2,-1,1,2} +
    integer scalar pin in [-4,4], each CERTIFIED unsolvable via
    :func:`certify_unsolvable` (exact rank check on linear graphs, empirical
    probe on nonlinear ones; accidental-solvable or gold-duplicate draws are
    resampled). When ``hard_negatives``, one distractor shares the gold
    insert_coeffs but differs in the defining factor's constant: a wrong scalar
    pin for scalar-pin golds, or the gold ``defining_expression`` shifted by a
    nonzero integer (e.g. ``"u - x**2"`` -> ``"u - x**2 - 2"``) for expression
    golds — it forces the policy to read constants, not just insertion topology.
    """
    if K < 2:
        raise ValueError("K must be >= 2 (gold + at least one distractor)")

    def unsolvable(cand: Candidate) -> bool:
        return certify_unsolvable(cand.apply(fixed), rng_seed=rng.randrange(2 ** 31))[
            "unsolvable"
        ]

    factor_ids = [f.id for f in fixed.factors]
    menu = [gold_candidate]
    seen = {_candidate_key(gold_candidate)}

    if hard_negatives:
        for _ in range(200):
            if gold_candidate.defining_expression is None:
                cand = Candidate(
                    gold_candidate.aux_var,
                    float(rng.randint(-4, 4)),
                    dict(gold_candidate.insert_coeffs),
                )
            else:
                delta = rng.choice((-4, -3, -2, -1, 1, 2, 3, 4))
                cand = Candidate(
                    gold_candidate.aux_var,
                    gold_candidate.pin_value + delta,
                    dict(gold_candidate.insert_coeffs),
                    f"{gold_candidate.defining_expression} - ({delta})",
                )
            if _candidate_key(cand) in seen:
                continue
            if unsolvable(cand):
                menu.append(cand)
                seen.add(_candidate_key(cand))
                break
        else:
            raise RuntimeError("could not certify a hard negative in 200 draws")

    attempts = 0
    while len(menu) < K:
        attempts += 1
        if attempts > 500:
            raise RuntimeError("could not fill the menu with certified distractors")
        subset = [fid for fid in factor_ids if rng.random() < 0.5]
        if not subset:
            continue
        cand = Candidate(
            gold_candidate.aux_var,
            float(rng.randint(-4, 4)),
            {fid: float(rng.choice((-2, -1, 1, 2))) for fid in subset},
        )
        if _candidate_key(cand) in seen:
            continue
        if not unsolvable(cand):
            continue  # accidental-solvable draw -> resample
        menu.append(cand)
        seen.add(_candidate_key(cand))

    rng.shuffle(menu)
    return menu, menu.index(gold_candidate)


# --- toy-variant resampler (main-only data source) ----------------------------

#: family -> (variable names,
#:            base factors as (factor_id, {var: coeff}),
#:            ELIGIBLE factor ids the latent u may touch — the gold's actual
#:            touched set is a per-instance random nonempty subset of these
#:            (DATA_VERSION 2), so gold support is NOT family-constant and a
#:            support-matching shortcut cannot identify the gold candidate.
#:            toy2's eligible set covers all equations for the same reason: a
#:            singleton set would make its gold support constant again.
_TEMPLATES: Dict[str, Tuple[Tuple[str, ...], List[Tuple[str, Dict[str, int]]], Tuple[str, ...]]] = {
    "toy1": (("x", "y"),
             [("eq1", {"x": 1, "y": 1}), ("eq2", {"x": 1, "y": -1}), ("eq3", {"x": 1})],
             ("eq1", "eq2", "eq3")),
    "toy2": (("x", "y", "z"),
             [("eq1", {"x": 1, "y": 1, "z": 1}), ("eq2", {"x": 1, "y": -1}),
              ("eq3", {"y": 1, "z": -1}), ("eq4", {"x": 1})],
             ("eq1", "eq2", "eq3", "eq4")),
    "toy3": (("x", "y"),
             [("eq1", {"x": 1}), ("eq2", {"y": 1}), ("eq3", {"x": 1, "y": 1})],
             ("eq1", "eq2")),
}

FAMILIES: Tuple[str, ...] = tuple(_TEMPLATES)

FAMILIES_BY_SOURCE: Dict[str, Tuple[str, ...]] = {
    "toys": FAMILIES,
    "aux_required": FAMILIES,  # contract C3 keeps the same family vocabulary
    "nonlinear": ("vieta", "quad_link"),
}


def _toy_variant(family: str, seed: int) -> Tuple[FactorGraph, Candidate, Dict[str, float]]:
    """Resample one instance of a structure_toys pattern with fresh integer
    constants/coefficients. Returns (fixed_graph, gold_candidate, augmented solution).

    Constants are chosen so the augmented system holds exactly at an integer gold
    solution; the fixed graph (u terms dropped) is certified inconsistent. The
    gold's touched-factor set is a random nonempty subset of the template's
    eligible ids, drawn once per (family, seed) — support randomization
    (DATA_VERSION 2) so gold support is not a family fingerprint.
    """
    # ponytail: local constant-resampler; superseded by marc.data.aux_required when present
    if family not in _TEMPLATES:
        raise ValueError(f"unknown family {family!r} (expected one of {FAMILIES})")
    var_names, base_factors, eligible = _TEMPLATES[family]
    rng = random.Random(f"toy_variant:{family}:{seed}")
    touched = tuple(rng.sample(eligible, rng.randint(1, len(eligible))))
    for _ in range(200):
        sol = {v: float(rng.randint(-3, 3)) for v in var_names}
        u0 = float(rng.choice((-4, -3, -2, -1, 1, 2, 3, 4)))  # u0 == 0 would leave fixed consistent
        coeffs = {fid: float(rng.choice((-2, -1, 1, 2))) for fid in touched}
        factors, edges = [], []
        for fid, terms in base_factors:
            const = -(sum(c * sol[v] for v, c in terms.items()) + coeffs.get(fid, 0.0) * u0)
            expr = " + ".join(f"({c})*{v}" for v, c in terms.items()) + f" + ({const})"
            factors.append(FactorNode(fid, expr))
            edges.extend(Edge(v, fid, float(c)) for v, c in terms.items())
        fixed = FactorGraph(
            variables=[VariableNode(v) for v in var_names], factors=factors, edges=edges
        )
        if not _is_inconsistent(fixed):
            continue
        # ponytail: keep the gold-augmented system inside the frozen baseline
        # solver's stability region. refine's polish (fixed lr=0.2) diverges when
        # lambda_max(A^T A) >= 10; resample stiff draws so gold_oracle (the
        # positive control) always solves. Ceiling: drop this filter if refine
        # ever gets a line search / adaptive lr.
        rows = [
            [float(terms.get(v, 0)) for v in var_names] + [coeffs.get(fid, 0.0)]
            for fid, terms in base_factors
        ]
        rows.append([0.0] * len(var_names) + [1.0])  # the aux-defining factor
        A = np.asarray(rows)
        if float(np.linalg.eigvalsh(A.T @ A)[-1]) >= 9.0:
            continue
        gold = Candidate(aux_var="u", pin_value=u0, insert_coeffs=coeffs)
        solution = dict(sol)
        solution["u"] = u0
        return fixed, gold, solution
    raise RuntimeError(f"could not sample an inconsistent {family} variant (seed={seed})")


# --- nonlinear aux-required families (source "nonlinear") ---------------------
#
# Built augmented-first, like _toy_variant: pick an integer gold solution, derive
# the constants so the augmented system holds exactly, then DROP the c*u terms to
# get the fixed graph. The rank certificate does not apply to these graphs, so
# both directions are checked empirically (asymmetric budgets):
#   fixed graph  — must FAIL the DEFAULT_PROBE (empirically unsolvable/unreachable
#                  at probe budget; real roots may exist — certificate="empirical")
#   gold-applied — must SOLVE at eval grade (REFERENCE_SOLVER: k=4, polish 4000)
# Draws failing either check are resampled.

_NONZERO = (-4, -3, -2, -1, 1, 2, 3, 4)


def _gold_lambda_max(aug: FactorGraph, solution: Dict[str, float]) -> float:
    """lambda_max(J^T J) of the augmented residuals' Jacobian at the gold solution.

    The nonlinear analogue of _toy_variant's stability filter: near a zero-residual
    solution the energy Hessian is J^T J, and the frozen reference polish
    (lr=0.2) diverges when lambda_max >= 10. Draws at or above 9.8 are resampled
    (thin margin on purpose — feasible vieta draws are rare, and the eval-grade
    solve gate remains the final arbiter for anything the filter lets through).
    """
    syms = [sp.Symbol(v.id) for v in aug.variables]
    subs = {sp.Symbol(k): v for k, v in solution.items()}
    J = np.array(
        [
            [float(sp.diff(sp.sympify(f.expression), s).subs(subs)) for s in syms]
            for f in aug.factors
        ]
    )
    return float(np.linalg.eigvalsh(J.T @ J)[-1])


def _nonlinear_variant(family: str, seed: int) -> Tuple[FactorGraph, Candidate, Dict[str, float]]:
    """Resample one nonlinear aux-required instance; returns
    (fixed_graph, gold_candidate, augmented solution incl. u)."""
    nl_fams = FAMILIES_BY_SOURCE["nonlinear"]
    if family not in nl_fams:
        raise ValueError(f"unknown nonlinear family {family!r} (expected one of {nl_fams})")
    rng = random.Random(f"nonlinear_variant:{family}:{seed}")
    # 1000 attempts: the cheap filters (constants + lambda_max) reject ~99% of
    # vieta draws; only survivors pay for the probe + eval-grade solve.
    for _ in range(1000):
        c1 = float(rng.choice((-2, -1, 1, 2)))
        c2 = float(rng.choice((-2, -1, 1, 2)))
        if family == "vieta":
            # augmented: x + y + c1*u = k1,  x*y + c2*u = k2,  u = x - y
            # ponytail: diversity ceiling — only |x*-y*| <= 2 draws survive the
            # lambda_max stability filter (J's y column carries x*, and vice
            # versa), so gold pins land in {+-1, +-2}. Same upgrade path as
            # quad_link: adaptive lr in refine lifts the bound.
            x_star = float(rng.choice(_NONZERO))
            y_star = float(rng.choice(_NONZERO))
            if y_star == x_star:
                continue  # u0 = x-y must be nonzero or fixed == augmented
            u0 = x_star - y_star
            k1 = x_star + y_star + c1 * u0
            k2 = x_star * y_star + c2 * u0
            if k1 ** 2 - 4 * k2 >= 0:
                continue  # fixed x+y=k1, x*y=k2 has real roots -> not aux-required
            exprs = [("eq1", f"x + y - ({k1})", {"x": 1, "y": 1}),
                     ("eq2", f"x*y - ({k2})", {"x": 1, "y": 1})]
            defining, sol = "u - (x - y)", {"x": x_star, "y": y_star}
        else:  # quad_link
            # augmented: 0.5*x**2 + 0.5*y + c1*u = k1,  0.5*x**2 - 0.5*y + c2*u = k2,
            # u = x**2. The 0.5 scale on the quadratic equations is load-bearing:
            # "u - x**2" alone puts 4*x*^2 into the x column of J, so integer golds
            # force x* = +-1 and unscaled equations would push lambda_max(J^T J) to
            # 12 — past the frozen polish's stability bound (10). At scale 0.5 the
            # c1=c2=-1 draws sit at lambda_max ~ 8.8, inside the filter.
            # ponytail: gold diversity ceiling — x* in {-1,1}, u0 = 1, c1 = c2 = -1
            # survive the stability filter; only y* and sign(x*) vary. Upgrade path:
            # a line search / adaptive lr in refine lifts the lambda_max bound.
            x_star = float(rng.choice((-1, 1)))
            y_star = float(rng.randint(-6, 6))
            u0 = x_star ** 2
            k1 = 0.5 * u0 + 0.5 * y_star + c1 * u0
            k2 = 0.5 * u0 - 0.5 * y_star + c2 * u0
            if k1 + k2 >= 0:
                continue  # fixed has real roots (0.5*x**2 = (k1+k2)/2)
            exprs = [("eq1", f"0.5*x**2 + 0.5*y - ({k1})", {"x": 1, "y": 0.5}),
                     ("eq2", f"0.5*x**2 - 0.5*y - ({k2})", {"x": 1, "y": -0.5})]
            defining, sol = "u - x**2", {"x": x_star, "y": y_star}
        fixed = FactorGraph(
            variables=[VariableNode(v) for v in ("x", "y")],
            factors=[FactorNode(fid, e) for fid, e, _ in exprs],
            edges=[Edge(v, fid, float(c)) for fid, _, terms in exprs for v, c in terms.items()],
        )
        gold = Candidate("u", u0, {"eq1": c1, "eq2": c2}, defining)
        solution = dict(sol)
        solution["u"] = u0
        aug = gold.apply(fixed)
        if _gold_lambda_max(aug, solution) >= 9.8:
            continue  # outside the frozen polish's stability region -> resample
        if not certify_unsolvable(fixed, rng_seed=rng.randrange(2 ** 31))["unsolvable"]:
            continue  # probe found a root of the fixed graph -> not aux-required
        if not _solvable_at_eval_grade(aug, rng_seed=rng.randrange(2 ** 31)):
            continue  # reference solver can't reach the gold basin -> resample
        return fixed, gold, solution
    raise RuntimeError(f"could not sample a certified {family} variant (seed={seed})")


def _pin_from_defining_expression(expression: str, aux_var: str) -> float:
    """v from a defining factor 'u - (v)': the expression at u=0 is -v."""
    expr = sp.sympify(expression)
    return float(-expr.subs(sp.Symbol(aux_var), 0))


def make_dataset(
    source: str,
    n: int,
    seed: int,
    K: int = 4,
    families: Optional[Sequence[str]] = None,
    hard_negatives: bool = True,
) -> List[InventionInstance]:
    """Build ``n`` menu-based invention instances.

    ``source="toys"`` uses the local toy-variant resampler (works on main today).
    ``source="aux_required"`` consumes ``marc.data.aux_required`` (contract C3) when
    present; raises an actionable ImportError otherwise. ``source="nonlinear"``
    uses the local nonlinear resampler (families ``vieta``/``quad_link``); those
    instances carry ``certificate="empirical"`` — see the module docstring for
    what that claim does and does not cover. Deterministic per
    ``(source, n, seed, K, families, hard_negatives)``.
    """
    fams = tuple(families) if families else FAMILIES_BY_SOURCE.get(source, FAMILIES)
    raw: List[Tuple[str, int, FactorGraph, Candidate, Dict[str, float]]] = []
    if source == "toys":
        for i in range(n):
            family = fams[i % len(fams)]
            inst_seed = seed + i
            fixed, gold, solution = _toy_variant(family, inst_seed)
            raw.append((family, inst_seed, fixed, gold, solution))
    elif source == "nonlinear":
        for i in range(n):
            family = fams[i % len(fams)]
            inst_seed = seed + i
            fixed, gold, solution = _nonlinear_variant(family, inst_seed)
            raw.append((family, inst_seed, fixed, gold, solution))
    elif source == "aux_required":
        try:
            from marc.data import aux_required
        except ImportError as exc:
            raise ImportError(
                "make_dataset(source='aux_required') needs marc/data/aux_required.py "
                "(contract C3: generate_instances(n, seed, patterns)), which is not on "
                "this branch yet. Use source='toys' (the local toy-variant resampler) "
                "or merge the aux_required data unit first."
            ) from exc
        for r in aux_required.generate_instances(n, seed, patterns=list(fams)):
            gold = Candidate(
                aux_var=r.aux_var,
                pin_value=_pin_from_defining_expression(r.defining_expression, r.aux_var),
                insert_coeffs={k: float(v) for k, v in r.insert_coeffs.items()},
            )
            raw.append((r.pattern, r.seed, r.fixed_graph, gold, dict(r.solution)))
    else:
        raise ValueError(f"unknown source {source!r} (expected one of {SOURCES})")

    if source == "nonlinear":
        n_restarts = DEFAULT_PROBE["n_seeds"] * DEFAULT_PROBE["k_refine"]
        certificate = "empirical"
        certificate_config = {
            **DEFAULT_PROBE,
            "claim": (
                f"each distractor failed a {n_restarts}-restart refine+Checker "
                "probe; 'exactly one solvable option' is an empirical claim at "
                "this probe budget, not a theorem"
            ),
        }
    else:
        certificate, certificate_config = "exact", None

    out: List[InventionInstance] = []
    for family, inst_seed, fixed, gold, solution in raw:
        rng = random.Random(f"menu:{family}:{inst_seed}:{K}:{hard_negatives}")
        menu, gold_idx = build_menu(fixed, gold, K, rng, hard_negatives=hard_negatives)
        out.append(
            InventionInstance(
                id=f"{source}_{family}_s{inst_seed}",
                family=family,
                seed=inst_seed,
                fixed_graph=fixed,
                candidates=menu,
                gold_idx=gold_idx,
                aux_value=float(solution[gold.aux_var]),
                solution=solution,
                certificate=certificate,
                certificate_config=dict(certificate_config) if certificate_config else None,
            )
        )
    return out


def to_padded(instance: InventionInstance) -> PaddedGraph:
    """Clean state c_0 over 2K slots: candidate j owns var slot 2j + factor slot 2j+1.

    Gold's var slot is VARIABLE carrying ``aux_value``; gold's factor slot is FACTOR
    carrying the pin value; every other slot is ABSENT/0.
    """
    K = len(instance.candidates)
    types = torch.full((2 * K,), ABSENT, dtype=torch.long)
    values = torch.zeros(2 * K, dtype=torch.float32)
    g = instance.gold_idx
    types[2 * g] = int(SlotType.VARIABLE)
    values[2 * g] = instance.aux_value
    types[2 * g + 1] = int(SlotType.FACTOR)
    values[2 * g + 1] = instance.candidates[g].pin_value
    return PaddedGraph(types, values)
