#!/usr/bin/env bash
# Assemble paper/tex/overleaf/ — exactly the files the Overleaf project needs, and nothing
# else. Regenerate rather than edit: the output is gitignored so there is never a second
# copy of main.tex in the repo to drift from the first.
#
#   bash scripts/make_overleaf.sh
#
# Then drag the contents of paper/tex/overleaf/ into Overleaf. Two documents live in one
# project: set the compiler to pdfLaTeX and the main document to main.tex to build the
# submission; switch the main document to supplement.tex to build the supplementary PDF.
set -euo pipefail

cd "$(dirname "$0")/.."
SRC=paper/tex
OUT=$SRC/overleaf

rm -rf "$OUT"
mkdir -p "$OUT/figures"

# the two documents plus the shared appendix body
cp "$SRC/main.tex" "$SRC/supplement.tex" "$SRC/marc_aaai_appendix.tex" "$OUT/"
# the AAAI-27 kit, unmodified, and the bibliography
cp "$SRC/aaai2027.sty" "$SRC/aaai2027.bst" "$SRC/refs.bib" "$OUT/"
# only the figures actually included by the two documents
for f in $(grep -ohE 'figures/[a-z_]+\.pdf' "$SRC/main.tex" "$SRC/marc_aaai_appendix.tex" | sort -u); do
  cp "$SRC/$f" "$OUT/figures/"
done

cat > "$OUT/README.txt" <<'TXT'
Overleaf project contents
=========================

Generated by scripts/make_overleaf.sh. Do not edit these copies; edit paper/tex/ in the
repository and regenerate, otherwise the two diverge.

Two documents share this project:

  main.tex        the submission. 7 content pages + references only.
  supplement.tex  the supplementary material, uploaded to AAAI as a SEPARATE document.
                  Both read marc_aaai_appendix.tex; supplement.tex \input's it, and its
                  floats are numbered S1..S5 / Figure S1.

Compiler must be pdfLaTeX. aaai2027.sty refuses to run under XeLaTeX or LuaLaTeX.

To build each one, set Overleaf's "Main document" (Menu > Main document) to main.tex or to
supplement.tex.

Before submitting, confirm on the built PDF:
  - the title renders (an earlier build came out with a blank title)
  - page 8 onward contains ONLY references; no body text, no statements
  - the appendix does NOT appear in main.pdf -- it is a separate upload
TXT

echo "wrote $OUT:"
find "$OUT" -type f | sort | sed 's|^|  |'
