#!/usr/bin/env bash
# Assemble the three self-contained upload bundles under paper/tex/.
#
#   bash scripts/make_overleaf.sh
#
#   paper/tex/overleaf/main/        -> the AAAI-27 submission PDF
#   paper/tex/overleaf/supplement/  -> the Technical Supplement PDF
#   (paper/tex/arxiv/ is built separately by scripts/make_arxiv.sh)
#
# Each is a standalone Overleaf project with exactly the files that document needs and
# nothing else, so there is no "Main document" switching and no way to compile one and
# upload the other by mistake. Each carries only the figures it actually includes.
#
# The output is gitignored; regenerate rather than edit, or the bundles drift from
# paper/tex/, which is the single source.
set -euo pipefail
cd "$(dirname "$0")/.."
SRC=paper/tex
OUT=$SRC/overleaf

rm -rf "$OUT"
mkdir -p "$OUT/main/figures" "$OUT/supplement/figures"

# ---- shared kit files: both documents need the style, the bst and the bibliography
for d in main supplement; do
  cp "$SRC/aaai2027.sty" "$SRC/aaai2027.bst" "$SRC/refs.bib" "$OUT/$d/"
done

# ---- the submission
cp "$SRC/main.tex" "$OUT/main/"
for f in $(grep -ohE 'figures/[a-z_]+\.pdf' "$SRC/main.tex" | sort -u); do
  cp "$SRC/$f" "$OUT/main/figures/"
done

# ---- the technical supplement (supplement.tex \input's the appendix body)
cp "$SRC/supplement.tex" "$SRC/marc_aaai_appendix.tex" "$OUT/supplement/"
for f in $(grep -ohE 'figures/[a-z_]+\.pdf' "$SRC/marc_aaai_appendix.tex" | sort -u); do
  cp "$SRC/$f" "$OUT/supplement/figures/"
done

cat > "$OUT/README.txt" <<'TXT'
Upload bundles
==============

Generated by scripts/make_overleaf.sh. Do not edit these copies; edit paper/tex/ and
regenerate, or they drift from the source.

  main/        Compile main.tex -> the AAAI-27 submission PDF.
               7 content pages plus references. The appendix is deliberately NOT here:
               AAAI-27 counts appendices bound into the main PDF against the page limit.

  supplement/  Compile supplement.tex -> the Technical Supplement PDF, uploaded to the
               separate OpenReview field. supplement.tex \input's marc_aaai_appendix.tex.
               The main paper cites this document 11 times (supplementary Tables S1, S3,
               S4, S5 and Appendices A, C, E), so it is not optional -- skipping it leaves
               eleven dangling pointers.

Both are separate Overleaf projects. Compiler must be pdfLaTeX; aaai2027.sty refuses
XeLaTeX and LuaLaTeX.

Before uploading, confirm on each built PDF:
  main.pdf        title renders; page 8 onward is references only; no appendix content
  supplement.pdf  Tables S1-S5 and Figure S1 all present; no unresolved references
Both must be free of author names -- the submission is double blind.
TXT

echo "wrote $OUT:"
find "$OUT" -type f | sort | sed 's|^|  |'
