#!/usr/bin/env bash
# Assemble paper/tex/arxiv/ — the de-anonymized preprint build.
#
#   bash scripts/make_arxiv.sh
#
# main.tex is DERIVED from paper/tex/main.tex rather than copied, so the body text can
# never drift between the submission and the preprint. Only three things change:
#
#   1. [submission] -> [preprint].  The submission option injects "This is an anonymized
#      submission ... Distribution, citation, or public sharing of this manuscript is
#      strictly prohibited", which would be actively false on arXiv. preprint drops the
#      copyright block and un-hides the author block.
#   2. the anonymous author line becomes the real author/affiliation block.
#   3. the technical appendix is inlined. arXiv has no page limit, so the preprint
#      carries everything in one PDF instead of pointing at a separate supplement.
#
# The output is gitignored; regenerate rather than edit.
set -euo pipefail
cd "$(dirname "$0")/.."
SRC=paper/tex
OUT=$SRC/arxiv

rm -rf "$OUT"; mkdir -p "$OUT/figures"
cp "$SRC/aaai2027.sty" "$SRC/aaai2027.bst" "$SRC/refs.bib" "$SRC/marc_aaai_appendix.tex" "$OUT/"
for f in $(grep -ohE 'figures/[a-z_]+\.pdf' "$SRC/main.tex" "$SRC/marc_aaai_appendix.tex" | sort -u); do
  cp "$SRC/$f" "$OUT/figures/"
done

python3 - "$SRC/main.tex" "$OUT/main.tex" <<'PY'
import re, sys, pathlib
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
s = src.read_text()

# 1. preprint, not submission
s = s.replace("\\usepackage[submission]{aaai2027}", "\\usepackage[preprint]{aaai2027}")

# 2. real author block, equal contribution for all four
authors = r"""\author{
    Quang Bui\equalcontrib\textsuperscript{\rm 1,\rm 2},
    Sparsh Roy\equalcontrib\textsuperscript{\rm 1,\rm 3},
    Akash Gundimeda\equalcontrib\textsuperscript{\rm 1,\rm 4},
    Davin Yin\equalcontrib\textsuperscript{\rm 1,\rm 5}
}
\affiliations{
    \textsuperscript{\rm 1}SAID Lab\\
    \textsuperscript{\rm 2}American International School Vienna\\
    \textsuperscript{\rm 3}Hopewell Valley Central High School\\
    \textsuperscript{\rm 4}Centennial High School\\
    \textsuperscript{\rm 5}Harvard University\\
    quangbui@mit.edu, sparshr@mit.edu, akash\_g@mit.edu, davin\_yin@college.harvard.edu
}"""
# replace only the anonymous author line (and the staged camera-ready comment block),
# keeping \title and \date intact
start = s.index("% Submission is double-blind")
end = s.index("\\author{Anonymous submission}") + len("\\author{Anonymous submission}")
s = s[:start] + authors + s[end:]

# 3. inline the appendix; arXiv has no page limit
s = s.replace("""% The technical appendix ships as a SEPARATE supplementary document,
% paper/tex/supplement.tex. AAAI-27 counts appendices bound into the main PDF
% against the 7 content pages and requires supplementary material to be
% uploaded separately, so it is no longer \\input here.
""", """% arXiv has no page limit, so the preprint carries the technical appendix inline.
\\onecolumn
\\appendix
\\setcounter{secnumdepth}{1}
\\input{marc_aaai_appendix}
""")
dst.write_text(s)
print(f"  derived {dst} from {src}")
PY

cat > "$OUT/README.txt" <<'TXT'
arXiv preprint build
====================

Generated by scripts/make_arxiv.sh. Do not edit these copies; edit paper/tex/ and
regenerate, or the preprint and the submission will diverge.

main.tex here is derived from paper/tex/main.tex. The body text is identical. The only
differences are the [preprint] style option (no anonymized-submission copyright notice),
the real author block, and the technical appendix inlined rather than shipped separately.

Compiler must be pdfLaTeX; aaai2027.sty refuses XeLaTeX and LuaLaTeX.

For arXiv upload, submit the .tex sources plus aaai2027.sty, aaai2027.bst, refs.bib and
figures/. arXiv runs its own LaTeX; upload main.bbl as well if its bibtex pass fails.
TXT

echo "wrote $OUT:"
find "$OUT" -type f | sort | sed 's|^|  |'
